### ISSUE TITLE
Refactor documentation round 2

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/mixs#42]
Comments from @cmungall:

- [x] full name not just short name
- [x] don’t bother including things like Usage
- [x] leave off mappings for now - there are no mappings in MIxS (yet)
- [x] put descriptions of classes (combos and packages and checklists) on the front page and just include a bit more text to let people know what is going on
- [ ] for classes, let’s generate a title that is not camelcase and use that (this is an upstream change though)
maybe show combos as a grid?
  * eg https://microbiomedata.github.io/mixs/fao_class/#fao_class
- [x] hyperlink URLs
- [ ] Maybe “Inheritance” is not so useful - we know everything has max one ancestor here?
- [ ] it’s not so useful to end up here - maybe exclude abstract classes?

**Comment by turbomam** [comment]
I'm excited that you're working on this @sujaypatil96 !

Here are [some additional new notes](https://docs.google.com/document/d/1y8p8ZaAYxyoABPeAFENCp7Hh-YYkZD9qpIA6ckLFt8o/edit). I'll try to merge in any other older notes I can find.

I can help with whatever parts you want
